project_id = "ninybkgnipuxmvcaxkwt"

[functions.send-trip-notifications]
verify_jwt = false

[functions.send-trip-created-notification]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-list-auth-users]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true